### ISSUE TITLE
Create an implementation of a generic map

### ISSUE THREAD

**Issue by jakejack13** [jakejack13/sos#13]
### Tasks
- [ ] Design an implementation for a generic map
- [ ] Implement `map_init`
- [ ] Implement `map_free`
- [ ] Implement `map_put`
- [ ] Implement `map_get`
- [ ] Implement `map_contains`
- [ ] Add test cases for each function
- [ ] Chec for memory leaks

**Comment by Altanis** [comment]
Want me to do this?
