### ISSUE TITLE
Create a process loader

### ISSUE THREAD

**Issue by jakejack13** [jakejack13/sos#14]
### Premise
The next step in development is to create a system that allows for "outside" programs to be allocated memory by a primitive loader and placed into a scheduler, allowing multiple processes to be run at once on one core. The systems to be created are as follows:

- Shell, used to run programs with arguments from a command line interface (will be created in a separate PR)
- Loader, used to allocate a stack for the requested process and fetch the correct data and global sections
- Pager, used to organize the different stacks allocated by different processes (will be created as part of #7 and #8 )
- Scheduler, used to run multiple programs concurrently on one core (will be created in a separate PR)

### Tasks
- [x] Create program and process definitions in `process.h`
- [x] Create sample program  and external linking in `process.c`
- [x] Add function definitions to `loader.h`
- [x] Implement the loader in `loader.c`
