### ISSUE TITLE
Create an initialization system for all operating system modules

### ISSUE THREAD

**Issue by jakejack13** [jakejack13/sos#17]
### Summary
With the growing number of systems that need to be initialized upon sos starting up, the kernel main loop has become cluttered with initialization function calls. Instead, we should refactor the statements into its own function in the kernel code, which is then called either during main or during boot. 

### Tasks
- [ ] Create a new function in `kernel.c` called `initialize()`
- [ ] Refactor all initialization function calls into `initialize()`
- [ ] Determine whether `initialize()` should be called in `kernel.c::main()` or `boot.S::_entry()`
