### ISSUE TITLE
Create per-system Makefile configuration

### ISSUE THREAD

**Issue by jakejack13** [jakejack13/sos#18]
### Summary
The Makefile is currently only configured for my own personal LLVM installation through Homebrew on my MacBook Pro. Other developers on this project do not have the same LLVM executable location. We need a way to automatically find the LLVM location on any given computer. 

### Tasks
- [ ] Detect if `llvm-config` exists on the system
- [ ] If `llvm-config` exists, use bin location from the tool for all LLVM operations
- [ ] If `llvm-config` does not exist, default to Homebrew location (already found in the current Makefile)
