### ISSUE TITLE
Create a simple shell for executing applications

### ISSUE THREAD

**Issue by jakejack13** [jakejack13/sos#25]
### Summary
With both our paging system and process loading and scheduling systems going up, we need a simple interface for a user to run a select program with arguments. This includes a prompt to notify the user that they should type as well as error handling (in case of an incorrect program name, for example).

### Tasks
- [ ] Implement the `process.c::program_search` function 
- [ ] Implement `shell.c::shell_run` 
- [ ] Design the look and feel of the shell (what it should look like, which error messages should be shown, etc.)
- [ ] Implement `shell.c::shell_main`
