### ISSUE TITLE
Create userspace implementation of sos

### ISSUE THREAD

**Issue by jakejack13** [jakejack13/sos#29]
### Summary
sos currently can only be run on a Raspberry Pi 4 system, which is inconvenient for contributors and maintainers that do not have such a system. Instead, this system should be able to run in userspace for easy testing.

### Tasks
- [x] Convert stdio to use glibc
- [x] Convert boot.S to use glibc _start
- [x] Create new linker script for userspace executable
- [x] Convert stdalloc to use proper memory segment
