### ISSUE TITLE
Create a test directory structure and unit test service that can run off-environment

### ISSUE THREAD

**Issue by jakejack13** [jakejack13/sos#5]
### Summary
As many of our developers are working with different environments, we need a way to test our kernel libraries in a hardware independent environment. This involves creating a configuration option that allows switching between hardware dependent and hardware independent libraries, such as stdio. It also involves creating a separate linker script and Makefile target so that compilation produces an executable rather than an image file. 

### Tasks
- [ ] Add a configuration option that allows a hardware independent/hardware dependent toggle (in this case, a macro variables that will be selected for at compile time. You should not give it a value in any file. You can check `config.h` for more information)
- [ ] Create test harnesses that replace hardware dependent libraries with hardware independent libraries (this involves using C macros in files such as`stdlib/stdio.c` to replace the implementations of the functions with ones from the standard C library glibc)
- [ ] Create a `tests` directory in the toplevel of the repo
- [ ] Create a testing library to create and run unit tests (take a look at https://github.com/jakejack13/jip for more information)
- [ ] Create an initialization file/function in the test library that replaces the symbols in the regular linking script with ones that can be used hardware independently 
- [ ] Create a test linker script to generate an executable (main linker script is `link.ld`)
- [ ] Add test targets to the Makefile to generate an executable (`make test`)

**Comment by farhannaqib** [comment]
im still going to use print statements 😎

**Comment by farhannaqib** [comment]
better late than never when it comes to unit testing
