### ISSUE TITLE
Create loader and scheduler for processes

### ISSUE THREAD

**Issue by jakejack13** [jakejack13/sos#6]
### Premise
The next step in development is to create a system that allows for "outside" programs to be allocated memory by a primitive loader and placed into a scheduler, allowing multiple processes to be run at once on one core. The systems to be created are as follows:
- Shell, used to run programs with arguments from a command line interface (will be created in a separate PR)
- Loader, used to allocate a stack for the requested process and fetch the correct data and global sections
- Pager, used to organize the different stacks allocated by different processes (will be created in a separate PR)
- Scheduler, used to run multiple programs concurrently on one core

### Tasks
- [ ] Create definitions for programs and processes
- [ ] Create function definitions and structs for the loader
- [ ] Create function definitions and structs for the scheduler
- [ ] Implement the loader
- [ ] Implement the scheduler
