### ISSUE TITLE
Create a page allocator

### ISSUE THREAD

**Issue by jakejack13** [jakejack13/sos#8]
### Summary

Before we can create a loader that will be able to set up memory properly for processes about to run, we need a way to allocate a stack, heap, text, and data section for each process. To do this, we will use a pager to request blocks of memory, called pages, from the kernel in order to fill our memory section needs. Your task involves creating this pager, which will serve users blocks of memory of fixed size from a specified area in memory. 

### Tasks
- [ ] Create global variables that will hold the state of the pager
- [ ] Implement `page_init()`
- [ ] Implement `page_alloc()`
- [ ] Implement `page_free()`

**Comment by anglesideangle** [comment]
i am *totally* qualified to do this
