### ISSUE TITLE
Prepare alloc library for paging system

### ISSUE THREAD

**Issue by jakejack13** [jakejack13/sos#9]
### Summary
Prepare source and header files for issues #7 and #8 

### Tasks
- [x] Remove old `heapalloc.c`
- [x] Remove `alloc.h`
- [x] Rename `globalalloc.c` to `heapalloc.c`
- [x] Create `heapalloc.h`
- [x] Add `struct heap_state` to `heapalloc.h`
- [x] Change `heapalloc.h` to conform to new specification
- [x] Modify linker script to add new memory section for pages
- [x] Create `pagealloc.c` and `pagealloc.h`
- [x] Modify `stdalloc.c` to conform to new `heapalloc` specification
